/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'stefan' at '09.09.16 11:19' with Gradle 3.0
 *
 * @author stefan, @date 09.09.16 11:19
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
