/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'stefan' at '09.09.16 11:19' with Gradle 3.0
 *
 * @author stefan, @date 09.09.16 11:19
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
